apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tdgl-generator
  namespace: tdgl
  labels:
    app: tdgl-generator
spec:
  arguments:
    parameters:
      - name: image
        value: ghcr.io/fangrh/tdgl-generator:45fd5d0
      - name: je-min
        value: "-1.0"
      - name: je-max
        value: "1.0"
      - name: je-count
        value: "10"
      - name: frames-per-je
        value: "5"
      - name: delay
        value: "2.0"
      - name: grid-y
        value: "72"
      - name: grid-x
        value: "72"
  entrypoint: generate
  serviceAccountName: argo-workflow
  templates:
    - name: generate
      container:
        image: "{{workflow.parameters.image}}"
        command:
          - python
          - -m
          - tdgl_generator.cli
          - --data-service-url=http://data-viewer.tdgl.svc.cluster.local
        env:
          - name: TDGL_JE_MIN
            value: "{{workflow.parameters.je-min}}"
          - name: TDGL_JE_MAX
            value: "{{workflow.parameters.je-max}}"
          - name: TDGL_JE_COUNT
            value: "{{workflow.parameters.je-count}}"
          - name: TDGL_FRAMES_PER_JE
            value: "{{workflow.parameters.frames-per-je}}"
          - name: TDGL_DELAY
            value: "{{workflow.parameters.delay}}"
          - name: TDGL_GRID_Y
            value: "{{workflow.parameters.grid-y}}"
          - name: TDGL_GRID_X
            value: "{{workflow.parameters.grid-x}}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      metadata:
        labels:
          app: tdgl-generator
