apiVersion: v1
kind: Secret
metadata:
  name: data-service-config
  namespace: tdgl
type: Opaque
stringData:
  TDGL_DATABASE_URL: "postgresql+psycopg://tdgl:tdgl-dev-password@postgres.tdgl.svc.cluster.local:5432/tdgl"