apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-tdgl-runner
  namespace: tdgl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-tdgl-runner
  template:
    metadata:
      labels:
        app: py-tdgl-runner
    spec:
      serviceAccountName: argo-workflow
      containers:
        - name: runner
          image: ghcr.io/fangrh/py-tdgl-runner:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: run-data
              mountPath: /data
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: run-data
          emptyDir: {}
