# Adapt: name, port mapping. Remove this file if service is internal-only.
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: tdgl
spec:
  selector:
    app: my-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP